from datetime import datetime, timedelta
import folium
from folium.plugins import TimestampedGeoJson
import csv
from pathlib import Path
import webbrowser

script_dir = Path(__file__).resolve().parent
csv_path = script_dir / "coords.csv"

coordinates = []

# Traverses thru the CSV file generated by the main analyzer program
# Puts them into a list format for use
with open(csv_path, mode = "r") as file:
    csv_reader = csv.reader(file, skipinitialspace = True)
    first_time = next(csv_reader)[0] #Time is in 1st row, as set up in analyzer file. Read this then proceed
    for row in csv_reader:
        if not row:
            continue #Skips empty rows

        lat = float(row[0])
        long = float(row[1])
        status = row[2].strip().lower() == "true"
        coordinates.append(([lat, long], status)) #Format of CSV file to be used


#When the receiver is turned off first the final series of packets will appear to fail to be received,
#although it is actually not due to transmission issues. Rather, it is due to the time offset
#To account for this I remove the final consecutive packets that are False in received status
i = len(coordinates) - 1
while i >= 0 and coordinates[i][1] == False:
    coordinates.pop()
    i -= 1



#Converts first_time to datetime format
start_time = datetime.fromisoformat(str(first_time))
features = []


all_geojson_coords = []
all_timestamps = []

for i, (coords, status) in enumerate(coordinates):
    lat, lon = coords
    current_time = (start_time + timedelta(seconds=i/10)).isoformat() #Progresses by 0.1 s, since BSM freq. is 10 Hz

    all_geojson_coords.append([lon, lat]) #GEOJSON uses long, lat as opposed to normal lat, long order
    all_timestamps.append(current_time)

    if status == True:
        dot_color = "#008000" # Green = received
    else:
        dot_color = "#ff0000" # Red = failed to receive

    #Creates a permanent colored point for each coordinate
    features.append(
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [lon, lat],  # GeoJSON expects [longitude, latitude]
            },
            "properties": {
                "times": [current_time],  # Only one timestamp makes it stay permanently
                "icon": "circle",         # Uses Leaflet's built-in vector circle marker
                "iconstyle": {
                    "color": dot_color,
                    "fillColor": dot_color,
                    "fillOpacity": 1.0,
                    "radius": 4,
                    "weight": 1     
                },
            },
        }
    )


geojson_data = {"type": "FeatureCollection", "features": features}

# Initialize map centered at the 1st coordinate
m = folium.Map(location=coordinates[0][0], zoom_start=16)

# Configs for rendering animation steps
TimestampedGeoJson(
    geojson_data,
    period="PT10S", #BSM frequency is 10 Hz, so gap is 100 ms
    duration=None,
    add_last_point=True,
    auto_play=True,
    loop=False,
    max_speed=10,
).add_to(m)


#Start marker
folium.Marker(
    location=coordinates[0][0],
    popup="Start",
    icon=folium.Icon(color="green", icon="play")
).add_to(m)

#End marker
folium.Marker(
    location=coordinates[-1][0],
    popup="End",
    icon=folium.Icon(color="red", icon="stop")
).add_to(m)





#Automatically opens up the HTML file in a browser
#Used in combination with the GUI button
webbrowser.open_new_tab("colored_car_path.html")